name: 'alumno9_proyecto'
version: '1.0.0'
config-version: 2

profile: 'alumno9_proyecto'


model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]
clean-targets:
  - "target"
  - "dbt_packages"


models:
  alumno9_proyecto:
    staging:
      +materialized: view
    marts:
      +materialized: table

snapshots:
  alumno9_proyecto:
    +target_database: alumno9_proyecto_silver
    +target_schema: snapshots
    +strategy: check
tests:
  alumno9_proyecto:
    +schema: workout_data
flags:
  require_generic_test_arguments_property: true