sources:
  - name: workout_data
    database: alumno9_proyecto_bronze
    schema: workout_data
    description: "Raw layer containing untransformed data extracted from different operational systems."
    tables:
      - name: exercises_raw
        description: "Contains detailed information about each exercise."
        columns:
          - name: exercise_id
            description: "Unique identifier for each exercise."
            tests:
              - not_null
              - unique
          - name: exercise_name
            description: "Name of the exercise"
            tests:
              - not_null
          - name: primary_muscle
            description: "Main muscle group"
            tests:
              - accepted_values:
                  arguments:
                    values: ['Quadriceps', 'Glutes', 'Hamstrings', 'Calves']
          - name: secondary_muscle
            description: "Additional muscle group"
          - name: movement_type
            description: "Type of movement performed"
            tests:
              - accepted_values:
                  arguments:
                    values: ['compound', 'isolation']
          - name: equipment
            description: "Equipment required"
            tests:
              - accepted_values:
                  arguments:
                    values: ['Barbell', 'Machine', 'Dumbbell', 'Cable']


      - name: muscle_activation_estimate_raw
        description: "Provides estimated muscle activation scores for each exercise."
        columns:
          - name: id
            description: "Unique identifier."
            tests:
              - not_null
              - unique
          - name: exercise_id
            description: "Reference to exercise."
            tests:
              - not_null
              - relationships:
                  arguments:
                    to: source('workout_data', 'exercises_raw')
                    field: exercise_id
          - name: muscle
            description: "Muscle name"
            tests:
              - not_null
          - name: activation_score
            description: "Numeric estimate of activation"
            tests:
              - not_null

      - name: sessions_raw
        description: "User session metadata."
        columns:
          - name: session_id
            tests:
              - not_null
              - unique
          - name: user_id
            tests:
              - not_null
              - relationships:
                  arguments:
                    to: source('workout_data', 'users_raw')
                    field: user_id
          - name: session_date
            tests:
              - not_null
          - name: session_goal
          - name: duration_min
          - name: subjective_effort
      - name: session_exercises_raw
        description: "Links exercises to sessions with training details."
        columns:
          - name: entry_id
            tests:
              - not_null
              - unique
          - name: session_id
            tests:
              - not_null
              - relationships:
                  arguments:
                    to: source('workout_data', 'sessions_raw')
                    field: session_id
          - name: exercise_id
            tests:
              - not_null
              - relationships:
                  arguments:
                    to: source('workout_data', 'exercises_raw')
                    field: exercise_id
          - name: sets
            tests:
              - not_null
          - name: reps
            tests:
              - not_null
          - name: weight_kg
            tests:
              - not_null
          - name: volume_kg
            tests:
              - not_null
          - name: estimated_1rm
            tests:
              - not_null


      - name: users_raw
        description: "User demographic info."
        columns:
          - name: user_id
            tests:
              - not_null
              - unique
          - name: first_name
          - name: last_name
          - name: age
          - name: sex
            tests:
              - accepted_values:
                  arguments:
                    values: ['F', 'M']
          - name: experience_level
            tests:
              - accepted_values:
                  arguments:
                    values: ['intermediate', 'advanced', 'beginner']